/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
/// * Material Design Icons, Copyright (C) Google, Inc
///         Author:    Google
///         License:   Apache 2.0 (https://www.apache.org/licenses/LICENSE-2.0)
///         Homepage:  https://design.google.com/icons/
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData camera_rear = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData camera_roll = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancel = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_giftcard = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_membership = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData card_travel = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData casino = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cast_connected = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData center_focus_strong = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData center_focus_weak = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData change_history = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chat_bubble_outline = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_box_outline_blank = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_left = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chevron_right = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child_care = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData child_friendly = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chrome_reader_mode = IconData(0xe816, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData check_circle = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData class_icon = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clear_all = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData close = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData closed_caption = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_circle = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_done = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_download = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_off = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_queue = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cloud_upload = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData code = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collections = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData collections_bookmark = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData color_lens = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
